name: Lint (type checking, security, code quality, ruff)

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10

      - name: Linting
        run: |
          pytest --cov=src/model --cov=src/preprocessor --cov=src/postprocessor --cov=src/pipeline   --cov-branch --cov-report term-missing
